In [4]:
import pandas as pd
url = "https://raw.githubusercontent.com/ogut77/DataScience/master/insurance.csv"
df = pd.read_csv(url)

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

Context in Insurance Data
This dataset is often used to predict charges based on the other variables (age, sex, bmi, children, smoker, region). For example:

Input Variables (X): age, sex, bmi, children, smoker, region (features used to make predictions).

Output Variable (y): charges (what you’re trying to predict).

Describtion of variables
1. Age
Description: The age of the individual (the insured person).
Type: Numerical (integer).
Example Values: 19, 45, 62, etc.
Role in Insurance: Age is a key factor in determining insurance charges. Older individuals often have higher medical costs (and thus higher charges) due to increased health risks.
2. Sex
Description: The gender of the individual.
Type: Categorical (text or binary).
Example Values: "male," "female"
Role in Insurance: Gender can influence insurance charges because health risks and medical expenses may differ between males and females (e.g., pregnancy-related costs for females).
3. BMI (Body Mass Index)
Description: A measure of body fat based on height and weight (calculated as weight in kg divided by height in meters squared).
Type: Numerical (float).
Example Values: 25.3, 30.1, 18.5, etc.
Role in Insurance: Higher BMI often correlates with increased health risks (e.g., obesity-related conditions like diabetes or heart disease), leading to higher insurance charges.
4. Children
Description: The number of children (dependents) covered under the individual’s insurance plan.
Type: Numerical (integer).
Example Values: 0, 1, 3, etc.
Role in Insurance: More children can increase insurance costs slightly, as it may reflect additional healthcare needs, though the effect is often less pronounced than other factors like smoking or age.
5. Smoker
Description: Indicates whether the individual smokes tobacco.
Type: Categorical (text or binary).
Example Values: "yes," "no" .
Role in Insurance: Smoking is a major factor in insurance charges. Smokers typically have much higher medical costs due to risks like lung disease or cancer, so their charges are significantly elevated.
6. Region
Description: The geographic region where the individual lives.
Type: Categorical (text).
Example Values: "northeast," "southeast," "southwest," "northwest" (common in U.S.-based datasets).
Role in Insurance: Charges can vary by region due to differences in healthcare costs, lifestyle factors, or local insurance regulations.
7. Charges
Description: The insurance charges (or premiums/costs) billed to the individual, typically in a currency like USD.
Type: Numerical (float).
Example Values: 1684.52, 11234.89, 32050.23, etc.
Role in Insurance: This is usually the target variable (output) in predictive modeling. It represents the amount the insurance company charges, influenced by all the other columns (age, sex, BMI, etc.).

In [5]:
#1. Check if there is null value in dataset df (5 pt)

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [10]:
#2. Assign charges to y  and others to X using df. y is output variable and X is input variables (5 pt)

y = df['charges']
X = df.drop('charges', axis=1)

In [11]:
#3. Use  get_dummies() function from the pandas library to convert categorical variables in a DataFrame (X).
# Drop first drops the first category’s dummy variable to avoid multicollinearity (5 pt)
X = pd.get_dummies(X, drop_first=True)

In [12]:
#Use following methods for the evaluation on test and train data
def evalmetric(y,ypred):
 from scipy.stats import pearsonr
 import numpy as np
 e = y - ypred
 mse_f = np.mean(e**2)
 rmse_f = np.sqrt(mse_f)
 mae_f = np.mean(abs(e))
 mape_f = 100*np.mean(abs(e/y))
 crl, _ = pearsonr(y, ypred)
 r2_f = crl*crl
 print("MSE:", mse_f)
 print("RMSE:", rmse_f)
 print("MAE:",mae_f)
 print("MAPE:",mape_f)
 print("R-Squared:", round(r2_f, 4))

In [14]:
# train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# train model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

# predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# evaluation
print("TRAIN RESULTS")
evalmetric(y_train, y_train_pred)

print("\nTEST RESULTS")
evalmetric(y_test, y_test_pred)

TRAIN RESULTS
MSE: 37277681.70201867
RMSE: 6105.545160099848
MAE: 4208.234572492226
MAPE: 42.20268508031651
R-Squared: 0.7417

TEST RESULTS
MSE: 33596915.85136145
RMSE: 5796.284659276273
MAE: 4181.19447375365
MAPE: 46.888255979146805
R-Squared: 0.7845

In [13]:
#4.Get the correlation between X variables and y variables.(5 pt)
corr = df.corr(numeric_only=True)['charges']
print(corr)

age         0.299008
bmi         0.198341
children    0.067998
charges     1.000000
Name: charges, dtype: float64

In [15]:
#5.Split a dataset into 25%  of data as test data  and 75% of data as training data ( pt)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [16]:
#6. Using Decision Tree and Linear Regression methods, compare the performance results on both test and training data
#to determine which one is more likely to overfit and which is more likely to underfit.
# Do you think that Lasso and Ridge regularization are more likely to improve the results of Linear model test data,
# or would Random Forest or Boosting methods are more likely to improve the results of Decison tree test data?
#Explain your reasoning.(35 pt)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

y_train_pred_lr = lr.predict(X_train)
y_test_pred_lr = lr.predict(X_test)

print("Linear Regression - TRAIN")
evalmetric(y_train, y_train_pred_lr)

print("\nLinear Regression - TEST")
evalmetric(y_test, y_test_pred_lr)

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

y_train_pred_dt = dt.predict(X_train)
y_test_pred_dt = dt.predict(X_test)

print("\nDecision Tree - TRAIN")
evalmetric(y_train, y_train_pred_dt)
print("\nDecision Tree - TEST")
evalmetric(y_test, y_test_pred_dt)

Linear Regression - TRAIN
MSE: 37004502.18409475
RMSE: 6083.132596294014
MAE: 4183.153367011969
MAPE: 42.26867490005659
R-Squared: 0.745

Linear Regression - TEST
MSE: 35117755.73613632
RMSE: 5926.023602394469
MAE: 4243.654116653137
MAPE: 44.468185116980976
R-Squared: 0.7676

Decision Tree - TRAIN
MSE: 182648.17106092346
RMSE: 427.37357318969015
MAE: 19.084122482552342
MAPE: 0.47775094523744194
R-Squared: 0.9987

Decision Tree - TEST
MSE: 36580230.16400095
RMSE: 6048.159237652473
MAE: 2693.294304847761
MAPE: 29.869257985320623
R-Squared: 0.7805

**Decision Tree**: Decision Trees are very flexible models and can easily learn complex patterns from the training data. Because of this, they often achieve very high performance on the training dataset but significantly worse performance on the test dataset. This indicates overfitting, meaning the model memorizes the training data instead of generalizing well to unseen data.

**Linear Regression:** Linear Regression is a simpler model that assumes a linear relationship between input variables and the output variable. Because it has limited flexibility, it may fail to capture complex patterns in the data. As a result, both train and test performance may be lower, which is a sign of underfitting.

**For Linear Regression:** Applying Lasso or Ridge regularization can improve the model. These techniques add penalties to large coefficients and help reduce model variance. This prevents the model from fitting noise in the training data and can improve performance on the test dataset.

**For Decision Trees:** Methods like Random Forest and Boosting are more effective improvements. These are ensemble techniques that combine multiple decision trees:



*   Random Forest reduces overfitting by averaging predictions from many trees trained on different subsets of data.

*   Boosting builds trees sequentially and focuses on correcting previous errors.

*   These ensemble approaches usually produce better generalization compared to a single decision tree.


Decision Trees are more likely to overfit, while Linear Regression is more likely to underfit.
Regularization techniques such as Lasso and Ridge can improve Linear Regression performance, while Random Forest and Boosting are more effective methods for improving Decision Tree performance by reducing overfitting and increasing prediction stability.

In [ ]:
#7. Explain performance of linear regressin on test data
# using  Root mean squared error, mean absolute error, mean absolute percentage error and R2 metric (10 pt)

**Explanation:**

The performance of the **Linear Regression model on the test dataset** is evaluated using several regression metrics:

**Root Mean Squared Error (RMSE)** measures the square root of the average squared difference between the actual values and predicted values. It shows how far the predictions are from the real values. Lower RMSE indicates that the model makes more accurate predictions.

**Mean Absolute Error (MAE)** calculates the average of the absolute differences between predicted and actual values. It represents the average prediction error without considering direction. A lower MAE means the predictions are closer to the true values.

**Mean Absolute Percentage Error (MAPE)** measures the average percentage difference between the predicted and actual values. It helps interpret the error in percentage terms. Smaller MAPE values indicate better prediction accuracy.

**R² (R-squared)** measures how well the model explains the variability of the target variable. Its value ranges from 0 to 1. A higher R² value means the model explains more of the variance in the data and has better predictive power.

Overall, **good model performance is indicated by low RMSE, MAE, and MAPE values and a high R² value**, which means the Linear Regression model predicts the test data accurately.

In [17]:
#8. Use Random Forest and Boosting methods (XGBoost, LightGBM, and CatBoost)
#to obtain the evaluation scores on  test data.
#Which Boosting technique yielded the best performance on the test data based on the R² metric?
#Did you achieve a better result compared to Random Forest on the test data based on the R² metric?
#If there is improvement on Random forest or boosting methods over decison tree, explain  (30 pt)

In [18]:
# Random Forest
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

y_test_pred_rf = rf.predict(X_test)

print("Random Forest - TEST")
evalmetric(y_test, y_test_pred_rf)

Random Forest - TEST
MSE: 23114410.14038345
RMSE: 4807.7448081593775
MAE: 2653.61478095801
MAPE: 30.27386314379988
R-Squared: 0.8506

In [19]:
# XGBoost
from xgboost import XGBRegressor

xgb = XGBRegressor(random_state=42)
xgb.fit(X_train, y_train)

y_test_pred_xgb = xgb.predict(X_test)

print("\nXGBoost - TEST")
evalmetric(y_test, y_test_pred_xgb)

XGBoost - TEST
MSE: 26433443.13176504
RMSE: 5141.346431798293
MAE: 2957.213261792119
MAPE: 34.57266690344694
R-Squared: 0.8301

In [20]:
# LightGBM
from lightgbm import LGBMRegressor

lgb = LGBMRegressor(random_state=42)
lgb.fit(X_train, y_train)

y_test_pred_lgb = lgb.predict(X_test)

print("\nLightGBM - TEST")
evalmetric(y_test, y_test_pred_lgb)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000377 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 319
[LightGBM] [Info] Number of data points in the train set: 1003, number of used features: 8
[LightGBM] [Info] Start training from score 13267.935814

LightGBM - TEST
MSE: 22005117.949021608
RMSE: 4690.961303296117
MAE: 2700.720352413941
MAPE: 33.101463593940274
R-Squared: 0.8553

In [22]:
!pip install xgboost lightgbm catboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.4 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [23]:
# CatBoost
from catboost import CatBoostRegressor

cat = CatBoostRegressor(verbose=0, random_state=42)
cat.fit(X_train, y_train)

y_test_pred_cat = cat.predict(X_test)

print("\nCatBoost - TEST")
evalmetric(y_test, y_test_pred_cat)

CatBoost - TEST
MSE: 21340838.308785602
RMSE: 4619.614519501124
MAE: 2608.117710576109
MAPE: 30.82075085150296
R-Squared: 0.8589